# fly.toml app configuration file generated for association-xyz on 2023-07-30T19:25:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "association-xyz"
primary_region = "cdg"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
